// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductManagementApi;

#nullable disable

namespace ProductManagementApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250319132057_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryCode = "ELE123",
                            CreatedDate = new DateTime(2025, 3, 19, 13, 20, 56, 496, DateTimeKind.Utc).AddTicks(3550),
                            IsActive = true,
                            Name = "Electronics"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryCode = "CLO456",
                            CreatedDate = new DateTime(2025, 3, 19, 13, 20, 56, 496, DateTimeKind.Utc).AddTicks(4350),
                            IsActive = true,
                            Name = "Clothing"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryCode = "BOK789",
                            CreatedDate = new DateTime(2025, 3, 19, 13, 20, 56, 496, DateTimeKind.Utc).AddTicks(4350),
                            IsActive = false,
                            Name = "Books"
                        });
                });

            modelBuilder.Entity("Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryName = "Electronics",
                            CreatedDate = new DateTime(2025, 3, 19, 13, 20, 56, 498, DateTimeKind.Utc).AddTicks(5120),
                            Description = "Latest smartphone with advanced features",
                            Name = "Smartphone",
                            Price = 699.99m,
                            ProductCode = "202310-001"
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryName = "Electronics",
                            CreatedDate = new DateTime(2025, 3, 19, 13, 20, 56, 498, DateTimeKind.Utc).AddTicks(6000),
                            Description = "High-performance laptop for professionals",
                            Name = "Laptop",
                            Price = 1299.99m,
                            ProductCode = "202310-002"
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryName = "Clothing",
                            CreatedDate = new DateTime(2025, 3, 19, 13, 20, 56, 498, DateTimeKind.Utc).AddTicks(6000),
                            Description = "Comfortable cotton t-shirt",
                            Name = "T-Shirt",
                            Price = 19.99m,
                            ProductCode = "202310-003"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
